# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vangogh',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/vangogh',
                'lib_path': 'vangogh'},
  'syms': {'vangogh.core': {'vangogh.core.foo': ('core.html#foo', 'vangogh/core.py')}}}
